apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: example-thing
  title: Template to show field validation
  description: look how cool
spec:
  type: template
  parameters:
    - title: Snapshot VM
      required:
        - serverNameOrPattern
        - nameSpace
      properties:
        serverNameOrPattern:
          title: serverNameOrPattern
          type: string
          description: FQDN or ansible host-string
          pattern: '^(\*|[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)(\.(\*|[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?))*$'
          ui:errorMessages:
            pattern: "Must be a valid FQDN or pattern (e.g., 'vm1.dev.local' or 'vm*.example.*.com')"
          ui:autofocus: true
          ui:options:
            rows: 5
          pattern: '^(\*|[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)(\.(\*|[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?))*$'
        nameSpace:
          title: nameSpace
          type: string
          description: OpenShift namespace of the VM to snapshot
          pattern: '^[a-zA-Z0-9-]+$'
          ui:errorMessages:
            pattern: "Can only contain letters, numbers, and dashes"
          ui:options:
            catalogFilter:
              kind: Group
          pattern: '^[a-zA-Z0-9-]+$'
  steps:
    - id: launch-job
      name: OpenShift / CNV / Create VM Snapshots
      action: rhaap:launch-job-template
      input:
        token: ${{ parameters.token }}
        values:
          template: OpenShift / CNV / Create VM Snapshots
          extraVariables:
            _hosts: ${{ parameters.serverNameOrPattern }}
            vm_namespace: ${{ parameters.nameSpace }}
